apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edgecloud-platform
spec:
  project: default
  source:
    repoURL: https://github.com/your/repo.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: edgecloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
